# Top level sections:
services:
#  service:
#   attribute:
#     - list syntax = blabla
#   other attribute:
#     mapping syntax: blabla
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb
    restart: always
    networks:
      - mynetwork
    volumes: # path in the container
      - database:/var/lib/mysql # mariadb writes in /var/lib/mysql by default
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "nc", "mariadb", "3306"] # ping mariadb to see if it's started
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 10
    env_file: ".env"
    environment: # set up the environment variables
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/rootpass # password for MariaDB root superuser account (_FILE is a convention because i'm using secrets)
      - MYSQL_PASSWORD_FILE=/run/secrets/userpass
    secrets:
      - userpass
      - rootpass

  wordpress:
    build: ./requirements/wordpress
    container_name: "wordpress"
    restart: always
    expose:
      - "9000" # used to define container ports that are exposed for communicating internally with other containers on the same network
    depends_on:
      mariadb:
        condition: service_healthy # compose also removes services in dependency order (wordpress before mariadb)
    env_file: ".env"
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/rootpass
      - MYSQL_PASSWORD_FILE=/run/secrets/userpass
    secrets:
      - userpass
      - rootpass
    volumes:
      - wordpress_data:/etc/data
    networks:
      - mynetwork

  nginx:
    build: ./requirements/nginx
    container_name: "nginx"
    depends_on:
      wordpress
    volumes:
      - wordpress_data:/etc/data
    networks:
      - mynetwork
    restart: always
    ports: # port mapping between host machine and container
      - "443:443"

networks:
  mynetwork:
    name: "mynetwork"

# configure named volumes that can be reused across multiple services
volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_data
# long form syntax for bind mounts, à changer

  # wordpress:
  #   name: wordpress

# this top-level secrets section defines the variables userpass and rootpass, and provides the file that populates their values
# the deployment of each container means Docker creates a bind mount under /run/secrets/<secret_name>
secrets:
  userpass:
    file: secrets/db_password.txt
  rootpass:
    file: secrets/db_root_password.txt
