version: "3"

services:

  mariadb:
    image: mariadb:12.2.2
    restart: always
    # environment:
    #   MARIADB_ROOT_PASSWORD: example
    networks:
      - monreseau
    volumes:
      - mariadbvolume
    ports:
      - '8080:9000'

  nginx:
    image: nginx:1.29.7
    depends_on:
      - mariadb

  wordpress:
    image: wordpress:6.9.4
    depends_on:
      - mariadb

networks:
  - monreseau

volumes:
  - mariadbvolume
