# FROM image + tag car sinon ça prend d'office le latest, on veut fixer la version

# chaque RUN crée un nouveau layer donc faire apt-get blabla && rm -rf fichiersinutiles ou alors multistage build

# Get latest version of mariadb
# FROM mariadb:12.2.2

# Set a working directory for the app
# WORKDIR /bin

# Copy all the files to the container in the root directory (relative the workdir) from tools directory
# COPY ./tools .
# add .dockerignore file to ignore what we want

# run commands from inside the workdir folder
# RUN sudo apt install mariadb-server

# EXPOSE 3306

# Launch "sh script.sh" command when the container start
# CMD ["sh", "script.sh"]
